### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by Mehonoshin** [cydev/vk#1]
Hello!

I'm looking for a suitable VK api client, found your repo, but it does not have any docs or examples :(
Of course I can read sources, but doc would save lots of time for everyone.

**Comment by ernado** [comment]
@Mehonoshin 
Привет! Этот репозиторий заброшен, последний коммит был около года назад - у меня отпала необходимость в API.

Извини, что тут нет примеров и документации, проект не допилен.
Я не советую использовать этот пакет, его архитектура не идеальна, код скорее всего содержит множество багов, и он вряд ли будет поддерживаться в ближайшее время. 

Удачи!

**Comment by Mehonoshin** [comment]
@ernado Ok
